server {
  listen 8080;
  root /usr/share/nginx/html;
  index index.html;

  # Cloud Run health and readiness probes
  location = /health {
    access_log off;
    default_type text/plain;
    return 200 'OK';
  }
  location = /ready {
    access_log off;
    default_type text/plain;
    return 200 'OK';
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
